ERROR:root:Exception occurred
Traceback (most recent call last):
  File "c:\Users\flore\Documents\Academics\CIT6\Computer Vision\log.py", line 7, in <module>
    app = QApplication(sys.argv)
          ^^^^^^^^^^^^
NameError: name 'QApplication' is not defined
